version: '3.5'

services:
  reverse-proxy:
    restart: unless-stopped 
    container_name: reverse-proxy
    image: ${REVERSE_PROXY_IMAGE:-reverse-proxy}
    ports:
      - ${PUB_PORT:-80}:${PUB_PORT:-80}
      - "443:443"
    # volumes:
    #   - ${CONFIG_DIR}:/etc/nginx/conf.d:z
    #   - ${STATIC_DIR}:/static:z
    #   # ${CERTS_DIR}:/etc/ssl/private:z
  dbapi:
    container_name: dbapi
    restart: unless-stopped
    image: ${DBAPI_IMAGE:-dbapi}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - TARGET=${TARGET:-production}
  db:
    container_name: vgac-db
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  # db-manager:
  #   container_name: db-manager
  #   restart: "no"
  #   image: ${DB_MANAGER_IMAGE:-db-manager}
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_HOST=${POSTGRES_HOST:-vgac-db}
  #   volumes:
  #     - ${DATA_DIR:-/data/faim/games}:/app/games:z
  #     - ${OUT_DIR:-/data/faim/out_data}:/app/out_dataset:z 
  expert:
    container_name: expert
    restart: unless-stopped
    image: ${EXPERT_IMAGE:-expert}
    environment:
      - TARGET=${TARGET:-production}
  single-tile:
    container_name: single-tile
    restart: unless-stopped
    image: ${SINGLE_TILE_IMAGE:-single-tile}
    environment:
      - TARGET=${TARGET:-production}


volumes:
  db-data:
    name: db-data

networks:
  default:
    name: vgac-network
