version: '3.5'

services:
  reverse-proxy-staging:
    restart: unless-stopped 
    container_name: reverse-proxy-staging
    image: ${REVERSE_PROXY_IMAGE:-reverse-proxy:master}
    volumes:
      -  ${CERTS_DIR}:/etc/ssl/private:z
    # ports:
    #   - ${PUB_PORT:-80}:${PUB_PORT:-80}
    #   - "443:443"
    #   - ${CONFIG_DIR}:/etc/nginx/conf.d:z
    #   - ${STATIC_DIR}:/staging:z
  dbapi-staging:
    container_name: dbapi-staging
    restart: unless-stopped
    image: ${DBAPI_IMAGE:-dbapi:master}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - TARGET=${TARGET:-staging}
  db-staging:
    container_name: vgac-db-staging
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data-staging:/var/lib/postgresql/data
  expert-staging:
    container_name: expert-staging
    restart: unless-stopped
    image: ${EXPERT_IMAGE:-expert:master}
    environment:
      - TARGET=${TARGET:-staging}
  single-tile-staging:
    container_name: single-tile-staging
    restart: unless-stopped
    image: ${SINGLE_TILE_IMAGE:-single-tile:master}
    environment:
      - TARGET=${TARGET:-production}

volumes:
  db-data-staging:
    name: db-data-staging

networks:
  default:
    name: vgac-network
