version: '3.5'

services:
  reverse:
    restart: unless-stopped
    hostname: reverse
    container_name: reverse
    image: nginx:1.17-alpine
    ports:
      - ${PUB_PORT:-80}:${PUB_PORT:-80}
      # - "443:443"
    volumes:
      - ${CONFIG_DIR}:/etc/nginx/conf.d:ro
      - ${STATIC_DIR}:/static:ro
      # ${CERTS_DIR}:/etc/ssl/private:ro
  dbapi:
    hostname: dbapi
    container_name: dbapi
    restart: unless-stopped
    image: ${DBAPI_IMAGE:-dbapi}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - TARGET=${TARGET:-production}
  db:
    hostname: vgac-db
    container_name: vgac-db
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  expert:
    hostname: expert
    container_name: expert
    restart: unless-stopped
    image: ${EXPERT_IMAGE:-expert}
    environment:
      - TARGET=${TARGET:-production}


volumes:
  db-data:
    name: db-data

networks:
  default:
    name: vgac-network
