version: '3.5'

services:
  reverse-proxy:
    restart: unless-stopped 
    container_name: reverse-proxy
    image: ${REVERSE_PROXY_IMAGE:-reverse-proxy}
    ports:
      - ${PUB_PORT:-80}:${PUB_PORT:-80}
      - "443:443"
    volumes:
      - ${CERTS_DIR:-./test}:/etc/nginx/certs:ro
      - ${STAGING_DIR:-./static}:/static/staging:z
    #   - ${CONFIG_DIR}:/etc/nginx/conf.d:z
    #   - ${STATIC_DIR}:/static:z
  dbapi:
    container_name: dbapi
    restart: unless-stopped
    image: ${DBAPI_IMAGE:-dbapi}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - TARGET=${TARGET:-production}
  db:
    container_name: vgac-db
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
  expert:
    container_name: expert
    restart: unless-stopped
    image: ${EXPERT_IMAGE:-expert}
    environment:
      - TARGET=${TARGET:-production}
  single-tile:
    container_name: single-tile
    restart: unless-stopped
    image: ${SINGLE_TILE_IMAGE:-single-tile}
    environment:
      - TARGET=${TARGET:-production}


volumes:
  db-data:
    name: db-data

networks:
  default:
    name: vgac-network
