version: '3.5'

services:
  reverse-proxy:
    volumes:
      - ${CERTS_DIR:-./test}:/etc/nginx/certs:ro
      - ${DEV_STATIC:-./static}:/static:z
    build:
      context: .
      dockerfile: Dockerfile-faim-nginx
    restart: "no"
  dbapi:
    build:
      context: ./dbapi
      dockerfile: Dockerfile-dbapi
    image: ${DBAPI_IMAGE:-dbapi}
    restart: "no"
  expert:
    build:
      context: ./expert
      dockerfile: Dockerfile-expert
    image: ${EXPERT_IMAGE:-expert}
    restart: "no"
  single-tile:
    build:
      context: ./single_tile_tagging
      dockerfile: Dockerfile-single-tile
    image: ${SINGLE_TILE_IMAGE:-single-tile}
    restart: "no"
  db-manager:
    build:
      context: ./db_manager
      dockerfile: Dockerfile-db-manager
    image: ${DB_MANAGER_IMAGE:-db-manager}
    restart: "no"
