version: '3.5'

services:
  reverse:
    container_name: reverse
    # restart: unless-stopped
    hostname: reverse
    image: nginx:stable-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./dev_config:/etc/nginx/conf.d
      - ./static:/static
      # - ./dev_config:/etc/ssl/private
  dbapi:
    container_name: dbapi
    hostname: dbapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dbapi
    ports:
      - "5000:5000"

networks:
  default:
    name: vgac-network
