FROM python:3.7-slim

WORKDIR /usr/src/app

COPY expert/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY expert/expert_tagging.py ./

EXPOSE 5000
CMD [ "python", "./expert_tagging.py" ]
